source('~/kaggle/AXA/AXA/Outliers_Estimation.R')
sample<-sample<-drivers.sample()
test<-outlier.qda(sample=sample,sample.drivers=c(2:200))
setwd("~/kaggle/AXA")
write.csv(test,"test2.csv",row.names=FALSE)